name: Keep Render Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # Ogni 10 minuti
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: |
          curl -X POST https://assistant-backend-4rw0.onrender.com/chat \
            -H "Content-Type: application/json" \
            -d '{"message": "ping", "system_message": "keep-alive", "temperature": 0.1, "top_p": 1.0}'
